name: publish_pages

on:
  push:
    branches: [main]

jobs:
  publish-pages:
    name: Publish pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
      - run: yarn install
      - run: yarn build
      - run: yarn push
